export const GET_CATEGORY = 'GET_CATEGORIES';
export const CLEAR_CATEGORIES = 'CLEAR_CATEGORIES';
export const GET_STANDARD_CATEGORIES = 'GET_STANDARD_CATEGORIES';
export const ADD_STANDARD_CATEGORIES = 'ADD_STANDARD_CATEGORIES';
export const UPDATE_CATEGORY_WITH_STANDARD = 'UPDATE_CATEGORY_WITH_STANDARD';